// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqyrwktqdzmdgzpyxpya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxeXJ3a3RxZHptZGd6cHl4cHlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzg2MDcsImV4cCI6MjA2MTk1NDYwN30.rraGLxOpb4yqMFFno5zk6GRY9KWRze2tSydL8fnDbfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);